[env:heltec_v4_mesh]
platform = platformio/espressif32@6.11.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
extra_scripts = pre:scripts/gen_build_time.py

build_flags =
        -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DRADIOLIB_STATIC_ONLY=1
    -DRADIOLIB_GODMODE=1

    ; ==== ПИНЫ LORA ДЛЯ HELTEC V4 ====
    -DP_LORA_NSS=8
    -DP_LORA_DIO_1=14
    -DP_LORA_RESET=12
    -DP_LORA_BUSY=13
    -DPIN_VEXT_EN=36
    -DPIN_VEXT_EN_ACTIVE=LOW
    ; ==== ПАРАМЕТРЫ LORA ====
    -DLORA_FREQ=868.731018
    -DLORA_BW=62.5
    -DLORA_SF=8
    -DLORA_TX_POWER=10
    -DLORA_SYNC_WORD=0x12
    -DLORA_PREAMBLE=16

    ; ==== SX1262 КОНФИГ ДЛЯ HELTEC V4 ====
    -DSX126X_DIO2_AS_RF_SWITCH=true
    -DSX126X_DIO3_TCXO_VOLTAGE=1.8
    -DSX126X_CURRENT_LIMIT=140
    -DSX126X_RX_BOOSTED_GAIN=1
    -DSX126X_REGISTER_PATCH=1

    ; ==== КЛАССЫ ДЛЯ MESHCORE ====
    -DRADIO_CLASS=CustomSX1262
    -DWRAPPER_CLASS=CustomSX1262Wrapper
    -I lib

lib_deps =
    SPI
    Wire
    https://github.com/jgromes/RadioLib.git#6d8934836678d8894e3d556550475b37dce3e2b6
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
    https://github.com/meshcore-dev/MeshCore.git